# Generated by Django 4.0.1 on 2022-07-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0002_alter_batteryusage_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='uid',
            field=models.CharField(max_length=50),
        ),
    ]
